### ISSUE TITLE
missing sitecode causes silent error

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/schwartz#5]
If a sitecode is missing, then the container fails without warning or messages.  Running without missing sitecode is fine.

Should we return missing pollution estimates in this case?  Or instruct user to remove rows with missing sitecodes?

**Comment by erikarasnick** [comment]
I think maybe return missing estimates? Would be consistent with the geocoder

**Comment by cole-brokamp** [comment]
Yes, I think that sounds good. Should we implement this in the R package or here in the container?

**Comment by erikarasnick** [comment]
implemented here https://github.com/geomarker-io/schwartzGeohashPM/pull/17

need to update schwartzGeohashPM to v0.0.6 in container
